doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver: pdo_mysql
        server_version: 8.0
        charset: utf8mb4
        types:
            # Burial
            burial_chain_id:            Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\Burial\BurialChainIdType
            burial_code:                Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\Burial\BurialCodeType
            burial_id:                  Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\Burial\BurialIdType
            burial_type:                Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\Burial\BurialTypeType
            customer_id:                Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\Burial\CustomerIdType
            # BurialContainer
            burial_container:           Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\BurialContainer\BurialContainerType
            # BurialPlace
            burial_place_id:            Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\BurialPlace\BurialPlaceIdType
            # BurialPlace/ColumbariumNiche
            columbarium_id:             Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\BurialPlace\ColumbariumNiche\ColumbariumIdType
            columbarium_name:           Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\BurialPlace\ColumbariumNiche\ColumbariumNameType
            columbarium_niche_id:       Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\BurialPlace\ColumbariumNiche\ColumbariumNicheIdType
            columbarium_niche_number:   Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\BurialPlace\ColumbariumNiche\ColumbariumNicheNumberType
            row_in_columbarium:         Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\BurialPlace\ColumbariumNiche\RowInColumbariumType
            # BurialPlace/GraveSite
            cemetery_block_id:          Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\BurialPlace\GraveSite\CemeteryBlockIdType
            cemetery_block_name:        Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\BurialPlace\GraveSite\CemeteryBlockNameType
            grave_site_id:              Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\BurialPlace\GraveSite\GraveSiteIdType
            grave_site_size:            Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\BurialPlace\GraveSite\GraveSiteSizeType
            position_in_row:            Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\BurialPlace\GraveSite\PositionInRowType
            row_in_block:               Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\BurialPlace\GraveSite\RowInBlockType
            # BurialPlace/MemorialTree
            memorial_tree_id:           Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\BurialPlace\MemorialTree\MemorialTreeIdType
            memorial_tree_number:       Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\BurialPlace\MemorialTree\MemorialTreeNumberType
            # CauseOfDeath
            cause_of_death_name:        Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\CauseOfDeath\CauseOfDeathNameType
            cause_of_death_id:          Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\CauseOfDeath\CauseOfDeathIdType
            # Contact
            address:                    Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\Contact\AddressType
            email:                      Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\Contact\EmailType
            phone_number:               Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\Contact\PhoneNumberType
            website:                    Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\Contact\WebsiteType
            # FuneralCompany
            funeral_company_id:         Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\FuneralCompany\FuneralCompanyIdType
            funeral_company_name:       Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\FuneralCompany\FuneralCompanyNameType
            funeral_company_note:       Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\FuneralCompany\FuneralCompanyNoteType
            # GeoPosition
            geo_position:               Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\GeoPosition\GeoPositionType
            # NaturalPerson
            full_name:                  Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\NaturalPerson\FullNameType
            natural_person_id:          Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\NaturalPerson\NaturalPersonIdType
            passport:                   Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\NaturalPerson\PassportType
            place_of_birth:             Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\NaturalPerson\PlaceOfBirthType
            # NaturalPerson/DeceasedDetails
            deceased_details:           Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\NaturalPerson\DeceasedDetails\DeceasedDetailsType
            # Organization
            okved:                      Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\Organization\OkvedType
            organization_name:          Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\Organization\NameType
            # Organization/BankDetails
            bank_details:               Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\Organization\BankDetails\BankDetailsType
            # Organization/JuristicPerson
            juristic_person_id:         Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\Organization\JuristicPerson\JuristicPersonIdType
            juristic_person_inn:        Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\Organization\JuristicPerson\InnType
            kpp:                        Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\Organization\JuristicPerson\KppType
            juristic_person_okpo:       Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\Organization\JuristicPerson\OkpoType
            ogrn:                       Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\Organization\JuristicPerson\OgrnType
            # Organization/SoleProprietor
            ogrnip:                     Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\Organization\SoleProprietor\OgrnipType
            sole_proprietor_id:         Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\Organization\SoleProprietor\SoleProprietorIdType
            sole_proprietor_inn:        Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\Organization\SoleProprietor\InnType
            sole_proprietor_okpo:       Cemetery\Registrar\Infrastructure\Persistence\Doctrine\Dbal\Types\Organization\SoleProprietor\OkpoType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Cemetery\Registrar:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Cemetery/Registrar/Infrastructure/Persistence/Doctrine/Orm/Mapping/MySQL'
                prefix: Cemetery\Registrar\Domain\Model
        dql:
            string_functions:
                JSON_EXTRACT: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonExtract
