version: '3'
services:
  registrar-nginx:
    build:
      context: ./docker
      dockerfile: nginx.docker
    volumes:
      - .:/app
    ports:
      - '8080:80'
    depends_on:
      - registrar-php-fpm
  registrar-php-fpm:
    build:
      context: ./docker
      dockerfile: php-fpm.docker
    volumes:
      - .:/app
    environment:
      APP_DEBUG: 1
  registrar-php-cli:
    build:
      context: ./docker
      dockerfile: php-cli.docker
    volumes:
      - .:/app
      - composer:/root/.composer/cache
    ports:
      - '9003:9003'
    environment:
      APP_DEBUG: 1
      PHP_IDE_CONFIG: 'serverName=Docker'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  registrar-mysql:
    image: mysql:8.0
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - '${DATABASE_HOST_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    restart: always
volumes:
  composer:
  mysql:
