<?php

declare(strict_types=1);

namespace Cemetery\Registrar\Domain\View\Burial;

/**
 * @author Nikolay Ryabkov <ZeroGravity.82@gmail.com>
 */
class BurialView
{
    public function __construct(
        public string  $id,
        public string  $code,
        public ?string $type,
        public ?string $deceasedNaturalPersonId,
        public ?string $deceasedNaturalPersonFullName,
        public ?string $deceasedNaturalPersonBornAt,
        public ?string $deceasedNaturalPersonDeceasedDetailsDiedAt,
        public ?int    $deceasedNaturalPersonDeceasedDetailsAge,
        public ?string $deceasedNaturalPersonDeceasedDetailsCauseOfDeathId,
        public ?string $deceasedNaturalPersonDeceasedDetailsDeathCertificateSeries,
        public ?string $deceasedNaturalPersonDeceasedDetailsDeathCertificateNumber,
        public ?string $deceasedNaturalPersonDeceasedDetailsDeathCertificateIssuedAt,
        public ?string $deceasedNaturalPersonDeceasedDetailsCremationCertificateNumber,
        public ?string $deceasedNaturalPersonDeceasedDetailsCremationCertificateIssuedAt,
        public ?string $customerId,
        public ?string $customerType,
        public ?string $customerNaturalPersonFullName,
        public ?string $customerNaturalPersonPhone,
        public ?string $customerNaturalPersonPhoneAdditional,
        public ?string $customerNaturalPersonEmail,
        public ?string $customerNaturalPersonAddress,
        public ?string $customerNaturalPersonBornAt,
        public ?string $customerNaturalPersonPlaceOfBirth,
        public ?string $customerNaturalPersonPassportSeries,
        public ?string $customerNaturalPersonPassportNumber,
        public ?string $customerNaturalPersonPassportIssuedAt,
        public ?string $customerNaturalPersonPassportIssuedBy,
        public ?string $customerNaturalPersonPassportDivisionCode,
        public ?string $customerSoleProprietorName,
        public ?string $customerSoleProprietorInn,
        public ?string $customerSoleProprietorOgrnip,
        public ?string $customerSoleProprietorOkpo,
        public ?string $customerSoleProprietorOkved,
        public ?string $customerSoleProprietorRegistrationAddress,
        public ?string $customerSoleProprietorActualLocationAddress,
        public ?string $customerSoleProprietorBankDetailsBankName,
        public ?string $customerSoleProprietorBankDetailsBik,
        public ?string $customerSoleProprietorBankDetailsCorrespondentAccount,
        public ?string $customerSoleProprietorBankDetailsCurrentAccount,
        public ?string $customerSoleProprietorPhone,
        public ?string $customerSoleProprietorPhoneAdditional,
        public ?string $customerSoleProprietorFax,
        public ?string $customerSoleProprietorEmail,
        public ?string $customerSoleProprietorWebsite,
        public ?string $customerJuristicPersonName,
        public ?string $customerJuristicPersonInn,
        public ?string $customerJuristicPersonKpp,
        public ?string $customerJuristicPersonOgrn,
        public ?string $customerJuristicPersonOkpo,
        public ?string $customerJuristicPersonOkved,
        public ?string $customerJuristicPersonLegalAddress,
        public ?string $customerJuristicPersonPostalAddress,
        public ?string $customerJuristicPersonBankDetailsBankName,
        public ?string $customerJuristicPersonBankDetailsBik,
        public ?string $customerJuristicPersonBankDetailsCorrespondentAccount,
        public ?string $customerJuristicPersonBankDetailsCurrentAccount,
        public ?string $customerJuristicPersonPhone,
        public ?string $customerJuristicPersonPhoneAdditional,
        public ?string $customerJuristicPersonFax,
        public ?string $customerJuristicPersonGeneralDirector,
        public ?string $customerJuristicPersonEmail,
        public ?string $customerJuristicPersonWebsite,
        public ?string $personInChargeId,
        public ?string $personInChargeFullName,
        public ?string $personInChargePhone,
        public ?string $personInChargePhoneAdditional,
        public ?string $personInChargeEmail,
        public ?string $personInChargeAddress,
        public ?string $personInChargeBornAt,
        public ?string $personInChargePlaceOfBirth,
        public ?string $personInChargePassportSeries,
        public ?string $personInChargePassportNumber,
        public ?string $personInChargePassportIssuedAt,
        public ?string $personInChargePassportIssuedBy,
        public ?string $personInChargePassportDivisionCode,
        public ?string $funeralCompanyId,
        public ?string $burialChainId,
        public ?string $burialPlaceId,
        public ?string $burialPlaceType,
        public ?string $burialPlaceGraveSiteCemeteryBlockId,
        public ?string $burialPlaceGraveSiteCemeteryBlockName,
        public ?int    $burialPlaceGraveSiteRowInBlock,
        public ?int    $burialPlaceGraveSitePositionInRow,
        public ?string $burialPlaceGraveSiteSize,
        public ?string $burialPlaceGraveSiteGeoPositionLatitude,
        public ?string $burialPlaceGraveSiteGeoPositionLongitude,
        public ?string $burialPlaceGraveSiteGeoPositionError,
        public ?string $burialPlaceColumbariumNicheColumbariumId,
        public ?string $burialPlaceColumbariumNicheColumbariumName,
        public ?int    $burialPlaceColumbariumNicheRowInColumbarium,
        public ?string $burialPlaceColumbariumNicheNumber,
        public ?string $burialPlaceColumbariumNicheGeoPositionLatitude,
        public ?string $burialPlaceColumbariumNicheGeoPositionLongitude,
        public ?string $burialPlaceColumbariumNicheGeoPositionError,
        public ?string $burialPlaceMemorialTreeNumber,
        public ?string $burialPlaceMemorialTreeGeoPositionLatitude,
        public ?string $burialPlaceMemorialTreeGeoPositionLongitude,
        public ?string $burialPlaceMemorialTreeGeoPositionError,
        public ?string $burialContainerType,
        public ?int    $burialContainerCoffinSize,
        public ?string $burialContainerCoffinShape,
        public ?bool   $burialContainerCoffinIsNonStandard,
        public ?string $buriedAt,
        public string  $createdAt,
        public string  $updatedAt,
    ) {}
}
