<?php

declare(strict_types=1);

namespace Cemetery\Registrar\Domain\View\Burial;

/**
 * @author Nikolay Ryabkov <ZeroGravity.82@gmail.com>
 */
class BurialView
{
    /**
     * @param string      $id
     * @param string      $code
     * @param string|null $type
     * @param string|null $deceasedId
     * @param string|null $deceasedNaturalPersonId
     * @param string|null $deceasedNaturalPersonFullName
     * @param string|null $deceasedNaturalPersonBornAt
     * @param string|null $deceasedDiedAt
     * @param int|null    $deceasedAge
     * @param string|null $deceasedDeathCertificateId
     * @param string|null $deceasedCauseOfDeathId
     * @param string|null $customerId
     * @param string|null $customerType
     * @param string|null $customerNaturalPersonFullName
     * @param string|null $customerNaturalPersonPhone
     * @param string|null $customerNaturalPersonPhoneAdditional
     * @param string|null $customerNaturalPersonEmail
     * @param string|null $customerNaturalPersonAddress
     * @param string|null $customerNaturalPersonBornAt
     * @param string|null $customerNaturalPersonPlaceOfBirth
     * @param string|null $customerNaturalPersonPassportSeries
     * @param string|null $customerNaturalPersonPassportNumber
     * @param string|null $customerNaturalPersonPassportIssuedAt
     * @param string|null $customerNaturalPersonPassportIssuedBy
     * @param string|null $customerNaturalPersonPassportDivisionCode
     * @param string|null $customerSoleProprietorName
     * @param string|null $customerSoleProprietorInn
     * @param string|null $customerSoleProprietorOgrnip
     * @param string|null $customerSoleProprietorOkpo
     * @param string|null $customerSoleProprietorOkved
     * @param string|null $customerSoleProprietorRegistrationAddress
     * @param string|null $customerSoleProprietorActualLocationAddress
     * @param string|null $customerSoleProprietorBankDetailsBankName
     * @param string|null $customerSoleProprietorBankDetailsBik
     * @param string|null $customerSoleProprietorBankDetailsCorrespondentAccount
     * @param string|null $customerSoleProprietorBankDetailsCurrentAccount
     * @param string|null $customerSoleProprietorPhone
     * @param string|null $customerSoleProprietorPhoneAdditional
     * @param string|null $customerSoleProprietorFax
     * @param string|null $customerSoleProprietorEmail
     * @param string|null $customerSoleProprietorWebsite
     * @param string|null $customerJuristicPersonName
     * @param string|null $customerJuristicPersonInn
     * @param string|null $customerJuristicPersonKpp
     * @param string|null $customerJuristicPersonOgrn
     * @param string|null $customerJuristicPersonOkpo
     * @param string|null $customerJuristicPersonOkved
     * @param string|null $customerJuristicPersonLegalAddress
     * @param string|null $customerJuristicPersonPostalAddress
     * @param string|null $customerJuristicPersonBankDetailsBankName
     * @param string|null $customerJuristicPersonBankDetailsBik
     * @param string|null $customerJuristicPersonBankDetailsCorrespondentAccount
     * @param string|null $customerJuristicPersonBankDetailsCurrentAccount
     * @param string|null $customerJuristicPersonPhone
     * @param string|null $customerJuristicPersonPhoneAdditional
     * @param string|null $customerJuristicPersonFax
     * @param string|null $customerJuristicPersonGeneralDirector
     * @param string|null $customerJuristicPersonEmail
     * @param string|null $customerJuristicPersonWebsite
     * @param string|null $burialPlaceOwnerId
     * @param string|null $burialPlaceOwnerFullName
     * @param string|null $burialPlaceOwnerPhone
     * @param string|null $burialPlaceOwnerPhoneAdditional
     * @param string|null $burialPlaceOwnerEmail
     * @param string|null $burialPlaceOwnerAddress
     * @param string|null $burialPlaceOwnerBornAt
     * @param string|null $burialPlaceOwnerPlaceOfBirth
     * @param string|null $burialPlaceOwnerPassportSeries
     * @param string|null $burialPlaceOwnerPassportNumber
     * @param string|null $burialPlaceOwnerPassportIssuedAt
     * @param string|null $burialPlaceOwnerPassportIssuedBy
     * @param string|null $burialPlaceOwnerPassportDivisionCode
     * @param string|null $funeralCompanyId
     * @param string|null $burialChainId
     * @param string|null $burialPlaceId
     * @param string|null $burialPlaceType
     * @param string|null $burialPlaceGraveSiteCemeteryBlockId
     * @param string|null $burialPlaceGraveSiteCemeteryBlockName
     * @param int|null    $burialPlaceGraveSiteRowInBlock
     * @param int|null    $burialPlaceGraveSitePositionInRow
     * @param string|null $burialPlaceGraveSiteSize
     * @param string|null $burialPlaceGraveSiteGeoPositionLatitude
     * @param string|null $burialPlaceGraveSiteGeoPositionLongitude
     * @param string|null $burialPlaceGraveSiteGeoPositionError
     * @param string|null $burialPlaceColumbariumNicheColumbariumId
     * @param string|null $burialPlaceColumbariumNicheColumbariumName
     * @param int|null    $burialPlaceColumbariumNicheRowInColumbarium
     * @param string|null $burialPlaceColumbariumNicheNumber
     * @param string|null $burialPlaceColumbariumNicheGeoPositionLatitude
     * @param string|null $burialPlaceColumbariumNicheGeoPositionLongitude
     * @param string|null $burialPlaceColumbariumNicheGeoPositionError
     * @param string|null $burialPlaceMemorialTreeNumber
     * @param string|null $burialPlaceMemorialTreeGeoPositionLatitude
     * @param string|null $burialPlaceMemorialTreeGeoPositionLongitude
     * @param string|null $burialPlaceMemorialTreeGeoPositionError
     * @param string|null $burialContainerType
     * @param int|null    $burialContainerCoffinSize
     * @param string|null $burialContainerCoffinShape
     * @param bool|null   $burialContainerCoffinIsNonStandard
     * @param string|null $buriedAt
     * @param string      $updatedAt
     */
    public function __construct(
        public readonly string  $id,
        public readonly string  $code,
        public readonly ?string $type,
        public readonly ?string $deceasedId,
        public readonly ?string $deceasedNaturalPersonId,
        public readonly ?string $deceasedNaturalPersonFullName,
        public readonly ?string $deceasedNaturalPersonBornAt,
        public readonly ?string $deceasedDiedAt,
        public readonly ?int    $deceasedAge,
        public readonly ?string $deceasedDeathCertificateId,
        public readonly ?string $deceasedCauseOfDeathId,
        public readonly ?string $customerId,
        public readonly ?string $customerType,
        public readonly ?string $customerNaturalPersonFullName,
        public readonly ?string $customerNaturalPersonPhone,
        public readonly ?string $customerNaturalPersonPhoneAdditional,
        public readonly ?string $customerNaturalPersonEmail,
        public readonly ?string $customerNaturalPersonAddress,
        public readonly ?string $customerNaturalPersonBornAt,
        public readonly ?string $customerNaturalPersonPlaceOfBirth,
        public readonly ?string $customerNaturalPersonPassportSeries,
        public readonly ?string $customerNaturalPersonPassportNumber,
        public readonly ?string $customerNaturalPersonPassportIssuedAt,
        public readonly ?string $customerNaturalPersonPassportIssuedBy,
        public readonly ?string $customerNaturalPersonPassportDivisionCode,
        public readonly ?string $customerSoleProprietorName,
        public readonly ?string $customerSoleProprietorInn,
        public readonly ?string $customerSoleProprietorOgrnip,
        public readonly ?string $customerSoleProprietorOkpo,
        public readonly ?string $customerSoleProprietorOkved,
        public readonly ?string $customerSoleProprietorRegistrationAddress,
        public readonly ?string $customerSoleProprietorActualLocationAddress,
        public readonly ?string $customerSoleProprietorBankDetailsBankName,
        public readonly ?string $customerSoleProprietorBankDetailsBik,
        public readonly ?string $customerSoleProprietorBankDetailsCorrespondentAccount,
        public readonly ?string $customerSoleProprietorBankDetailsCurrentAccount,
        public readonly ?string $customerSoleProprietorPhone,
        public readonly ?string $customerSoleProprietorPhoneAdditional,
        public readonly ?string $customerSoleProprietorFax,
        public readonly ?string $customerSoleProprietorEmail,
        public readonly ?string $customerSoleProprietorWebsite,
        public readonly ?string $customerJuristicPersonName,
        public readonly ?string $customerJuristicPersonInn,
        public readonly ?string $customerJuristicPersonKpp,
        public readonly ?string $customerJuristicPersonOgrn,
        public readonly ?string $customerJuristicPersonOkpo,
        public readonly ?string $customerJuristicPersonOkved,
        public readonly ?string $customerJuristicPersonLegalAddress,
        public readonly ?string $customerJuristicPersonPostalAddress,
        public readonly ?string $customerJuristicPersonBankDetailsBankName,
        public readonly ?string $customerJuristicPersonBankDetailsBik,
        public readonly ?string $customerJuristicPersonBankDetailsCorrespondentAccount,
        public readonly ?string $customerJuristicPersonBankDetailsCurrentAccount,
        public readonly ?string $customerJuristicPersonPhone,
        public readonly ?string $customerJuristicPersonPhoneAdditional,
        public readonly ?string $customerJuristicPersonFax,
        public readonly ?string $customerJuristicPersonGeneralDirector,
        public readonly ?string $customerJuristicPersonEmail,
        public readonly ?string $customerJuristicPersonWebsite,
        public readonly ?string $burialPlaceOwnerId,
        public readonly ?string $burialPlaceOwnerFullName,
        public readonly ?string $burialPlaceOwnerPhone,
        public readonly ?string $burialPlaceOwnerPhoneAdditional,
        public readonly ?string $burialPlaceOwnerEmail,
        public readonly ?string $burialPlaceOwnerAddress,
        public readonly ?string $burialPlaceOwnerBornAt,
        public readonly ?string $burialPlaceOwnerPlaceOfBirth,
        public readonly ?string $burialPlaceOwnerPassportSeries,
        public readonly ?string $burialPlaceOwnerPassportNumber,
        public readonly ?string $burialPlaceOwnerPassportIssuedAt,
        public readonly ?string $burialPlaceOwnerPassportIssuedBy,
        public readonly ?string $burialPlaceOwnerPassportDivisionCode,
        public readonly ?string $funeralCompanyId,
        public readonly ?string $burialChainId,
        public readonly ?string $burialPlaceId,
        public readonly ?string $burialPlaceType,
        public readonly ?string $burialPlaceGraveSiteCemeteryBlockId,
        public readonly ?string $burialPlaceGraveSiteCemeteryBlockName,
        public readonly ?int    $burialPlaceGraveSiteRowInBlock,
        public readonly ?int    $burialPlaceGraveSitePositionInRow,
        public readonly ?string $burialPlaceGraveSiteSize,
        public readonly ?string $burialPlaceGraveSiteGeoPositionLatitude,
        public readonly ?string $burialPlaceGraveSiteGeoPositionLongitude,
        public readonly ?string $burialPlaceGraveSiteGeoPositionError,
        public readonly ?string $burialPlaceColumbariumNicheColumbariumId,
        public readonly ?string $burialPlaceColumbariumNicheColumbariumName,
        public readonly ?int    $burialPlaceColumbariumNicheRowInColumbarium,
        public readonly ?string $burialPlaceColumbariumNicheNumber,
        public readonly ?string $burialPlaceColumbariumNicheGeoPositionLatitude,
        public readonly ?string $burialPlaceColumbariumNicheGeoPositionLongitude,
        public readonly ?string $burialPlaceColumbariumNicheGeoPositionError,
        public readonly ?string $burialPlaceMemorialTreeNumber,
        public readonly ?string $burialPlaceMemorialTreeGeoPositionLatitude,
        public readonly ?string $burialPlaceMemorialTreeGeoPositionLongitude,
        public readonly ?string $burialPlaceMemorialTreeGeoPositionError,
        public readonly ?string $burialContainerType,
        public readonly ?int    $burialContainerCoffinSize,
        public readonly ?string $burialContainerCoffinShape,
        public readonly ?bool   $burialContainerCoffinIsNonStandard,
        public readonly ?string $buriedAt,
        public readonly string  $updatedAt,
    ) {}
}
