<?php

declare(strict_types=1);

namespace Cemetery\Registrar\Application\Burial;

/**
 * @author Nikolay Ryabkov <ZeroGravity.82@gmail.com>
 */
final class BurialFormView
{
    public function __construct(
        public readonly string  $id,
        public readonly string  $code,
        public readonly ?string $type,
        public readonly ?string $deceasedId,
        public readonly ?string $deceasedNaturalPersonId,
        public readonly ?string $deceasedNaturalPersonFullName,
        public readonly ?string $deceasedNaturalPersonBornAt,
        public readonly ?string $deceasedDiedAt,
        public readonly ?int    $deceasedAge,
        public readonly ?string $deceasedDeathCertificateId,
        public readonly ?string $deceasedCauseOfDeath,
        public readonly ?string $customerId,
        public readonly ?string $customerType,
        public readonly ?string $customerNaturalPersonFullName,
        public readonly ?string $customerNaturalPersonPhone,
        public readonly ?string $customerNaturalPersonPhoneAdditional,
        public readonly ?string $customerNaturalPersonEmail,
        public readonly ?string $customerNaturalPersonAddress,
        public readonly ?string $customerNaturalPersonBornAt,
        public readonly ?string $customerNaturalPersonPlaceOfBirth,
        public readonly ?string $customerNaturalPersonPassportSeries,
        public readonly ?string $customerNaturalPersonPassportNumber,
        public readonly ?string $customerNaturalPersonPassportIssuedAt,
        public readonly ?string $customerNaturalPersonPassportIssuedBy,
        public readonly ?string $customerNaturalPersonPassportDivisionCode,
        public readonly ?string $customerSoleProprietorName,
        public readonly ?string $customerSoleProprietorInn,
        public readonly ?string $customerSoleProprietorOgrnip,
        public readonly ?string $customerSoleProprietorOkpo,
        public readonly ?string $customerSoleProprietorOkved,
        public readonly ?string $customerSoleProprietorRegistrationAddress,
        public readonly ?string $customerSoleProprietorActualLocationAddress,
        public readonly ?string $customerSoleProprietorBankDetails,
        public readonly ?string $customerSoleProprietorPhone,
        public readonly ?string $customerSoleProprietorPhoneAdditional,
        public readonly ?string $customerSoleProprietorFax,
        public readonly ?string $customerSoleProprietorEmail,
        public readonly ?string $customerSoleProprietorWebsite,
        public readonly ?string $customerJuristicPersonName,
        public readonly ?string $customerJuristicPersonInn,
        public readonly ?string $customerJuristicPersonKpp,
        public readonly ?string $customerJuristicPersonOgrn,
        public readonly ?string $customerJuristicPersonOkpo,
        public readonly ?string $customerJuristicPersonOkved,
        public readonly ?string $customerJuristicPersonLegalAddress,
        public readonly ?string $customerJuristicPersonPostalAddress,
        public readonly ?string $customerJuristicPersonBankDetails,
        public readonly ?string $customerJuristicPersonPhone,
        public readonly ?string $customerJuristicPersonPhoneAdditional,
        public readonly ?string $customerJuristicPersonFax,
        public readonly ?string $customerJuristicPersonGeneralDirector,
        public readonly ?string $customerJuristicPersonEmail,
        public readonly ?string $customerJuristicPersonWebsite,
        public readonly ?string $burialPlaceOwnerId,
        public readonly ?string $burialPlaceOwnerFullName,
        public readonly ?string $burialPlaceOwnerPhone,
        public readonly ?string $burialPlaceOwnerPhoneAdditional,
        public readonly ?string $burialPlaceOwnerEmail,
        public readonly ?string $burialPlaceOwnerAddress,
        public readonly ?string $burialPlaceOwnerBornAt,
        public readonly ?string $burialPlaceOwnerPlaceOfBirth,
        public readonly ?string $burialPlaceOwnerPassportSeries,
        public readonly ?string $burialPlaceOwnerPassportNumber,
        public readonly ?string $burialPlaceOwnerPassportIssuedAt,
        public readonly ?string $burialPlaceOwnerPassportIssuedBy,
        public readonly ?string $burialPlaceOwnerPassportDivisionCode,
        public readonly ?string $funeralCompanyId,
        public readonly ?string $funeralCompanyType,
        public readonly ?string $funeralCompanySoleProprietorName,
        public readonly ?string $funeralCompanySoleProprietorInn,
        public readonly ?string $funeralCompanySoleProprietorOgrnip,
        public readonly ?string $funeralCompanySoleProprietorOkpo,
        public readonly ?string $funeralCompanySoleProprietorOkved,
        public readonly ?string $funeralCompanySoleProprietorRegistrationAddress,
        public readonly ?string $funeralCompanySoleProprietorActualLocationAddress,
        public readonly ?string $funeralCompanySoleProprietorBankName,
        public readonly ?string $funeralCompanySoleProprietorBik,
        public readonly ?string $funeralCompanySoleProprietorCorrespondentAccount,
        public readonly ?string $funeralCompanySoleProprietorCurrentAccount,
        public readonly ?string $funeralCompanySoleProprietorPhone,
        public readonly ?string $funeralCompanySoleProprietorPhoneAdditional,
        public readonly ?string $funeralCompanySoleProprietorFax,
        public readonly ?string $funeralCompanySoleProprietorEmail,
        public readonly ?string $funeralCompanySoleProprietorWebsite,
        public readonly ?string $funeralCompanyJuristicPersonName,
        public readonly ?string $funeralCompanyJuristicPersonInn,
        public readonly ?string $funeralCompanyJuristicPersonKpp,
        public readonly ?string $funeralCompanyJuristicPersonOgrn,
        public readonly ?string $funeralCompanyJuristicPersonOkpo,
        public readonly ?string $funeralCompanyJuristicPersonOkved,
        public readonly ?string $funeralCompanyJuristicPersonLegalAddress,
        public readonly ?string $funeralCompanyJuristicPersonPostalAddress,
        public readonly ?string $funeralCompanyJuristicPersonBankName,
        public readonly ?string $funeralCompanyJuristicPersonBik,
        public readonly ?string $funeralCompanyJuristicPersonCorrespondentAccount,
        public readonly ?string $funeralCompanyJuristicPersonCurrentAccount,
        public readonly ?string $funeralCompanyJuristicPersonPhone,
        public readonly ?string $funeralCompanyJuristicPersonPhoneAdditional,
        public readonly ?string $funeralCompanyJuristicPersonFax,
        public readonly ?string $funeralCompanyJuristicPersonGeneralDirector,
        public readonly ?string $funeralCompanyJuristicPersonEmail,
        public readonly ?string $funeralCompanyJuristicPersonWebsite,
        public readonly ?string $burialChainId,
        public readonly ?string $burialPlaceId,
        public readonly ?string $burialPlaceType,
        public readonly ?string $burialPlaceGraveSiteCemeteryBlockId,
        public readonly ?string $burialPlaceGraveSiteCemeteryBlockName,
        public readonly ?int    $burialPlaceGraveSiteRowInBlock,
        public readonly ?int    $burialPlaceGraveSitePositionInRow,
        public readonly ?string $burialPlaceGraveSiteSize,
        public readonly ?string $burialPlaceColumbariumNicheColumbariumId,
        public readonly ?string $burialPlaceColumbariumNicheColumbariumName,
        public readonly ?int    $burialPlaceColumbariumNicheRowInColumbarium,
        public readonly ?string $burialPlaceColumbariumNicheNicheNumber,
        public readonly ?string $burialPlaceMemorialTreeNumber,
        public readonly ?string $burialPlaceGeoPositionLatitude,
        public readonly ?string $burialPlaceGeoPositionLongitude,
        public readonly ?string $burialPlaceGeoPositionError,
        public readonly ?string $burialContainerType,
        public readonly ?int    $burialContainerCoffinSize,
        public readonly ?string $burialContainerCoffinShape,
        public readonly ?bool   $burialContainerCoffinIsNonStandard,
        public readonly ?string $buriedAt,
        public readonly string  $updatedAt,
    ) {}
}
